import Image from "next/image";
import {RevealObserver,WordCycle} from "@/components/ClientEffects";
import {wa,type Topic} from "@/components/whatsapp";

const solutions:{id:string;question:string;answer:string;topic:Topic}[]=[
{id:"01",question:"Seu marketing gera oportunidades de verdade?",answer:"Posicionamento, conteúdo, mídia e estratégia comercial conectados.",topic:"clientes"},
{id:"02",question:"Seu atendimento depende de alguém estar disponível?",answer:"Automação e inteligência artificial para responder, organizar e avançar conversas.",topic:"automacao"},
{id:"03",question:"Seu site apresenta valor ou apenas ocupa um endereço?",answer:"Experiências digitais rápidas, premium e construídas para converter.",topic:"site"},
{id:"04",question:"Sua marca é reconhecida pelo que realmente entrega?",answer:"Identidade, linguagem e posicionamento para aumentar percepção e confiança.",topic:"marca"},
{id:"05",question:"O ativo mais importante da sua empresa está protegido?",answer:"Registro de marca com acompanhamento especializado do início ao fim.",topic:"registro"}
];
function W({topic,children,className=""}:{topic:Topic;children:React.ReactNode;className?:string}){return <a href={wa(topic)} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>}
export default function Home(){return <>
<RevealObserver/><div className="noise"/>
<header className="header"><a href="#inicio" className="headerLogo"><Image src="/assets/a7one-logo.png" alt="A7 One" width={880} height={280} priority/></a><nav><a href="#visao">Visão</a><a href="#solucoes">Soluções</a><a href="#experiencia">Experiência</a></nav><W topic="geral" className="headerButton">Falar com a Dani <span>↗</span></W></header>
<main>
<section id="inicio" className="hero"><div className="heroGrid"/><div className="heroGlow glowOne"/><div className="heroGlow glowTwo"/>
<div className="heroCopy"><div className="kicker"><i/> MARKETING • GROWTH • AI</div><h1>Crescer não é fazer mais.<br/>É construir <WordCycle/></h1><p>A A7 One conecta estratégia, marketing, tecnologia e inteligência artificial para transformar desafios empresariais em crescimento estruturado.</p><div className="heroButtons"><W topic="diagnostico" className="button buttonPrimary">Descobrir meu próximo passo</W><a href="#solucoes" className="button buttonGhost">Ver como podemos ajudar</a></div><div className="heroMeta"><span>Estratégia antes da ferramenta</span><span>Execução conectada ao resultado</span></div></div>
<div className="heroObject"><div className="orbit orbitOne"/><div className="orbit orbitTwo"/><div className="metalCard"><Image src="/assets/a7one-logo.png" alt="" width={880} height={280}/><div className="metalLine"/><small>ESTRATÉGIA PARA A PRÓXIMA FASE</small></div><div className="signal signalOne">ESTRATÉGIA</div><div className="signal signalTwo">TECNOLOGIA</div><div className="signal signalThree">INTELIGÊNCIA ARTIFICIAL</div></div></section>

<section id="visao" className="vision"><div className="sectionTag" data-reveal>01 / VISÃO</div><div className="visionIntro"><h2 data-reveal>O próximo nível não começa com uma ferramenta.</h2><p data-reveal>Começa quando visão, operação e tecnologia passam a trabalhar na mesma direção.</p></div><div className="visionStage" data-reveal><article><span>01</span><h3>Enxergar</h3><p>Identificar o que realmente limita o crescimento.</p></article><article><span>02</span><h3>Decidir</h3><p>Escolher prioridades e construir uma direção clara.</p></article><article><span>03</span><h3>Executar</h3><p>Conectar marketing, tecnologia e inteligência artificial.</p></article><article className="active"><span>04</span><h3>Escalar</h3><p>Transformar esforço em processo, previsibilidade e resultado.</p></article></div></section>

<section id="solucoes" className="solutions"><div className="solutionsHeader"><div data-reveal><div className="sectionTag">02 / SOLUÇÕES</div><h2>Qual problema está impedindo sua empresa de avançar?</h2></div><p data-reveal>Não começamos oferecendo um pacote. Começamos entendendo o que precisa mudar.</p></div><div className="solutionRows">{solutions.map(s=><a key={s.id} href={wa(s.topic)} target="_blank" rel="noopener noreferrer" className="solution" data-reveal><span className="solutionNumber">{s.id}</span><div><h3>{s.question}</h3><p>{s.answer}</p></div><span className="solutionCta">Conversar sobre isso <b>↗</b></span></a>)}</div></section>

<section id="experiencia" className="experience"><div className="experienceText" data-reveal><div className="sectionTag">03 / EXPERIÊNCIA</div><h2>Você explica.<br/>A Dani organiza o próximo passo.</h2><p>Uma conversa direta, guiada e sem formulários intermináveis. A Dani entende sua necessidade, faz as perguntas certas e encaminha o contexto para a equipe.</p><W topic="diagnostico" className="textLink">Começar uma conversa <span>↗</span></W></div><div className="chatFrame" data-reveal><div className="chatHeader"><div className="daniStatus"><i/> Dani online</div><span>A7 One</span></div><div className="chatBody"><div className="message userMessage">Minha empresa cresceu, mas o atendimento virou um gargalo.</div><div className="message daniMessage">Entendi. Hoje vocês perdem mais tempo respondendo, organizando contatos ou acompanhando oportunidades?</div><div className="typingDots"><i/><i/><i/></div></div><div className="chatFooter"><span>Conversa direcionada, contexto preservado.</span><W topic="automacao">Abrir WhatsApp ↗</W></div></div></section>

<section className="method"><div className="methodHeader" data-reveal><div className="sectionTag">04 / COMO PENSAMOS</div><h2>Três competências. Uma única direção.</h2></div><div className="methodGrid"><article data-reveal><span>01</span><div className="methodIcon targetIcon"/><h3>Estratégia</h3><p>Clareza para escolher o que fazer — e o que não fazer.</p></article><article data-reveal><span>02</span><div className="methodIcon systemIcon"/><h3>Tecnologia</h3><p>Estrutura para reduzir atrito, integrar processos e ganhar velocidade.</p></article><article data-reveal><span>03</span><div className="methodIcon aiIcon"/><h3>Inteligência Artificial</h3><p>Capacidade para atender, organizar e aprender em escala.</p></article></div></section>

<section className="automation" data-reveal><div className="automationVisual"><div className="automationPulse"/><div className="automationCore"><span>24/7</span><small>ATENDIMENTO</small></div></div><div className="automationCopy"><div className="sectionTag">AUTOMAÇÃO APLICADA</div><h2>Seu atendimento pode continuar mesmo quando sua equipe para.</h2><p>A automação aparece como solução para um problema real — não como um produto solto no meio da página.</p><W topic="automacao" className="button buttonPrimary">Automatizar meu atendimento</W></div></section>

<section className="final"><div data-reveal><div className="sectionTag">05 / PRÓXIMA DECISÃO</div><h2>O próximo passo da sua empresa pode começar com uma conversa.</h2><p>Conte para a Dani o que está acontecendo. A gente organiza o caminho.</p><W topic="geral" className="button buttonPrimary">Falar com a Dani agora</W></div><div className="daniPanel" data-reveal><div className="daniOrb"><i/></div><strong>Dani</strong><span>Atendimento A7 One</span><small><i/> online agora</small></div></section>
</main>
<footer><Image src="/assets/a7one-logo.png" alt="A7 One" width={880} height={280}/><div><a href="mailto:contato@a7one.com.br">contato@a7one.com.br</a><a href="https://www.instagram.com/a7one.ai/" target="_blank">Instagram</a><a href="https://www.linkedin.com/company/a7one/" target="_blank">LinkedIn</a></div><small>© 2026 A7 One — Marketing • Growth • AI</small></footer>
</>}
